

sudo: required
services:
   - docker


before_install:
   - docker build -t react-test -f ./client/Dockerfile.dev ./client


script:
   - docker run -e CI=true react-test npm test -- --coverage


after_success:
   - docker build -t project2-client ./client
   - docker build -t project2-nginx ./nginx
   - docker build -t project2-server ./server
   - docker build -t project2-worker ./worker
   
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   
   - docker push project2-client
   - docker push project2-nginx
   - docker push project2-server
   - docker push project2-worker


